apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookslib-prod
  namespace: argocd
spec:
  project: bookslib
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/walsptr/gitops.git
    targetRevision: main
    path: argocd/apps/prod
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
