apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: books-service-secrets
  namespace: bookslib-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: books-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: bookslib/prod/books-service
        property: connection_string
