apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: bookslib-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_DSN
      remoteRef:
        key: bookslib/prod/auth-service
        property: db_dsn
