apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookslib-dev-auth-service
  namespace: argocd
spec:
  project: bookslib
  destination:
    server: https://kubernetes.default.svc
    namespace: bookslib-dev
  sources:
    - repoURL: https://github.com/walsptr/bookslib.git
      targetRevision: main
      path: helm/auth-service
      helm:
        valueFiles:
          - $values/environments/dev/auth-service.values.yaml
    - repoURL: https://github.com/walsptr/gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
