apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookslib-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: bookslib
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  source:
    repoURL: https://github.com/walsptr/gitops.git
    targetRevision: main
    path: gateway
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

