apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookslib-prod-books-service
  namespace: argocd
spec:
  project: bookslib
  destination:
    server: https://kubernetes.default.svc
    namespace: bookslib-prod
  sources:
    - repoURL: https://github.com/walsptr/bookslib.git
      targetRevision: main
      path: helm/books-service
      helm:
        valueFiles:
          - $values/environments/prod/books-service.values.yaml
    - repoURL: https://github.com/walsptr/gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
