apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reviews-service-secrets
  namespace: bookslib-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: reviews-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: bookslib/dev/reviews-service
        property: db_password
