image:
  repository: sywlsptr/books-service
  tag: 9de8fd0
fullnameOverride: books-service
secrets:
  existingSecretName: books-service-secrets
  keys:
    connectionString: ConnectionStrings__DefaultConnection
