image:
  repository: sywlsptr/books-service
  tag: f9378fe
fullnameOverride: books-service
secrets:
  existingSecretName: books-service-secrets
  keys:
    connectionString: ConnectionStrings__DefaultConnection
