image:
  repository: sywlsptr/books-service
  tag: 095b99c
fullnameOverride: books-service
secrets:
  existingSecretName: books-service-secrets
  keys:
    connectionString: ConnectionStrings__DefaultConnection
