image:
  repository: sywlsptr/reviews-service
  tag: 11af732
fullnameOverride: reviews-service
db:
  name: reviews_db
  user: user
  host: 192.168.113.52
secrets:
  existingSecretName: reviews-service-secrets
  keys:
    dbPassword: DB_PASSWORD
